/**
 * Type Definitions Index
 * Central export point for all TypeScript types
 */

// API Types
export type {
  ApiResponse,
  PaginatedResponse,
  ApiError,
  LoginCredentials,
  RegisterData,
  AuthResponse,
  RefreshTokenRequest,
  CreateChannelRequest,
  UpdateChannelRequest,
  ChannelValidationResponse,
  CreatePostRequest,
  UpdatePostRequest,
  SchedulePostRequest,
  RealTimeMetrics,
  RealTimeDataPoint,
  BatchAnalyticsResponse,
  UploadResponse,
  StorageFilesResponse,
  HealthCheckResponse,
  InitialDataResponse,
  RequestConfig,
  ApiClientConfig,
  AuthStrategy,
  ExportType,
  ExportFormat,
  ExportRequest,
  ExportResponse,
} from './api';

// Domain Models
export type {
  User,
  UserRole,
  UserPreferences,
  Channel,
  ChannelMetrics,
  ChannelSettings,
  ChannelValidationResult,
  Post,
  PostStatus,
  PostMetadata,
  ScheduledPost,
  AnalyticsOverview,
  GrowthMetrics,
  GrowthDataPoint,
  ReachMetrics,
  TopPost,
  PostDynamics,
  EngagementMetrics,
  BestTimeRecommendation,
  MediaFile,
  MediaType,
  MediaMetadata,
  UploadProgress,
  PendingMedia,
  TimePeriod,
  DateRange,
  AnalyticsPeriod,
  DataSource,
  SystemHealth,
  Alert,
  ValidationResult,
  ValidationErrors,
  PaginationParams,
  PaginatedResult,
  ChartType,
  ChartDataPoint,
  ChartSeries,
  ChartConfig,
  ContentOptimizationSuggestion,
  ContentAnalysis,
  SecurityThreat,
  ChurnPrediction,
  NotificationType,
  Notification,
  LoadingState,
  SortOrder,
  Theme,
  Optional,
  Nullable,
  ID,
  Timestamp,
  ApiStatus,
} from './models';

// Component Props
export type {
  BaseComponentProps,
  LoadingProps,
  PaginationProps,
  HeaderProps,
  SidebarProps,
  PageContainerProps,
  DashboardPageProps,
  MetricsCardProps,
  AnalyticsDashboardProps,
  AddChannelProps,
  ChannelListProps,
  ChannelSelectorProps,
  ChannelCardProps,
  PostCreatorProps,
  ScheduledPostsListProps,
  PostCardProps,
  MediaUploaderProps,
  MediaPreviewProps,
  StorageFileBrowserProps,
  AnalyticsOverviewCardProps,
  GrowthChartProps,
  TopPostsTableProps,
  PostViewDynamicsChartProps,
  EngagementMetricsCardProps,
  BestTimeCardsProps,
  ChartVisualizationProps,
  ChartTypeSelectorProps,
  TimeRangeControlsProps,
  ButtonProps,
  InputProps,
  SelectProps,
  ModalProps,
  ToastProps,
  AlertBoxProps,
  LoadingSpinnerProps,
  EmptyStateProps,
  ErrorBoundaryProps,
  DataTableProps,
  StatsCardProps,
  ProgressBarProps,
  FormProps,
  FormFieldProps,
  SearchBarProps,
  FilterPanelProps,
  GlobalDataSourceSwitchProps,
  DataSourceBadgeProps,
  DiagnosticPanelProps,
  ContentOptimizerProps,
  SecurityMonitoringProps,
  ChurnPredictorProps,
} from './components';

// Store Types
export type {
  AuthState,
  ChannelState,
  PostState,
  AnalyticsState,
  MediaState,
  UIState,
  AppStores,
  AsyncAction,
  AsyncActionWithParam,
  StoreSelector,
  StoreCreator,
  PersistConfig,
  DevtoolsConfig,
  AsyncStateSlice,
  AsyncStateActions,
  UseAuthStore,
  UseChannelStore,
  UsePostStore,
  UseAnalyticsStore,
  UseMediaStore,
  UseUIStore,
  UseAuthSelector,
  UseChannelSelector,
  UsePostSelector,
  UseAnalyticsSelector,
  UseMediaSelector,
  UseUISelector,
} from './store';

// Note: All types are exported above via re-exports
// No need for convenience re-exports to avoid duplicates
