# Bandit config (YAML)
exclude_dirs:
  - tests

# Agar xohlasang, aniq qoida(lar)ni ham o‘chirib turish mumkin:
# skips:
#   - B101   # tests ichida assert ishlatilganligi uchun
#   - B105   # placeholder 'replace_me'ni # noseс bilan allaqachon yoptik
