repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # ✅ ENABLED: MyPy for Apps Layer (100% Type Safe - 161 errors fixed!)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        name: mypy (apps layer - 100% type safe ✅)
        # Only check the fully type-safe apps subdirectories
        files: ^apps/(bot|shared|api)/
        # Exclude areas not yet fully typed (core/infra have 629 errors to fix later)
        exclude: ^apps/(mtproto|demo|celery|di)/
        args:
          - --config-file=mypy.ini
        additional_dependencies:
          - types-aiofiles==25.1.0.20251011
          - types-requests==2.32.4.20250913
          - types-PyYAML
          - types-redis

  - repo: local
    hooks:
      - id: forbid-cross-imports
        name: 🛡️  Clean Architecture Import Guard
        entry: python3 scripts/guard_imports.py
        language: system
        types: [python]
        description: "Prevent core/ from importing apps/ or infra/ modules"
        exclude: ^(core/services/payment/|tests/|bot/database/migrations/|docs/|scripts/)
        pass_filenames: false
        always_run: true
