# Compose v2 (version: mayli, kerak emas)
# .env dagi qiymatlar BARCHA servislar uchun yuklanadi


services:
  postgres:
    image: postgres:16
    container_name: analyticbot-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-analytic_bot}
      POSTGRES_USER: ${POSTGRES_USER:-analytic}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change_me}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-analytic} -d ${POSTGRES_DB:-analytic_bot}"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: analyticbot-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  # --- API (FastAPI/Uvicorn) ---
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analyticbot-api
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+asyncpg://${POSTGRES_USER:-analytic}:${POSTGRES_PASSWORD:-change_me}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-analytic_bot}}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: >
      uvicorn api:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  # --- Telegram bot ---
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analyticbot-bot
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+asyncpg://${POSTGRES_USER:-analytic}:${POSTGRES_PASSWORD:-change_me}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-analytic_bot}}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: python run_bot.py
    restart: unless-stopped

  # --- Celery worker ---
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analyticbot-celery-worker
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+asyncpg://${POSTGRES_USER:-analytic}:${POSTGRES_PASSWORD:-change_me}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-analytic_bot}}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A bot.celery_app worker -l info
    restart: unless-stopped

  # --- Celery beat (scheduler) ---
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analyticbot-celery_beat
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+asyncpg://${POSTGRES_USER:-analytic}:${POSTGRES_PASSWORD:-change_me}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-analytic_bot}}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A bot.celery_app beat -l info
    restart: unless-stopped


volumes:
  pgdata:
