# AnalyticBot - Tool Configuration
# Dependencies are managed via pip-tools (requirements.in -> requirements.txt)

[tool.coverage.run]
source = ["apps", "core", "infra"]
branch = true
omit = [
    "*/tests/*",
    "*/migrations/*",
    "*/venv/*",
    "*/__pycache__/*",
    "docs/*",
    "scripts/*",
    "infra/docker/*",
    "infra/k8s/*",
    "infra/terraform/*",
    "infra/helm/*"
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "class .*\\bProtocol\\):",
    "@(abc\\.)?abstractmethod",
]

[tool.ruff]
line-length = 100
target-version = "py311"
exclude = [
    "docs/_archive/**",
    "docs/archive/**",
    "**/migrations/**",
    "**/venv/**",
    "**/__pycache__/**",
]

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q --cov=apps --cov=core --cov=infra --cov-report=term-missing --cov-report=html --cov-fail-under=80"
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
markers = [
    "unit: Unit tests",
    "integration: Integration tests",
    "e2e: End-to-end tests",
    "performance: Performance tests",
    "security: Security tests",
    "slow: Slow running tests"
]

[project]
name = "analyticbot"
version = "0.1.0"
description = "AnalyticBot for Telegram"
requires-python = ">=3.11"
dependencies = [
    "aiogram==3.*",
    "aiogram_i18n>=1.4",
    "fastapi==0.116.*",
    "uvicorn[standard]==0.30.*",
    "SQLAlchemy[asyncio]==2.*",
    "asyncpg==0.29.*",
    "psycopg2-binary==2.*",
    "alembic==1.*",
    "celery[redis]==5.*",
    "redis==5.*",
    "pydantic==2.*",
    "pydantic-settings==2.*",
    "dependency-injector==4.*",
    "punq>=0.7.0",
    "telethon>=1.32.0",
    "slowapi>=0.1.9",
    "opentelemetry-api>=1.20.0",
    "opentelemetry-sdk>=1.20.0",
    "opentelemetry-exporter-otlp-proto-grpc>=1.20.0",
    "opentelemetry-instrumentation-requests>=0.41b0",
    "opentelemetry-instrumentation-asyncpg>=0.41b0",
    "Pillow>=10.0.0",
    "urlextract==1.*",
    "python-dotenv==1.*",
    "python-multipart==0.0.*",
    "prometheus-client==0.17.*",
    "gunicorn==21.*",
    "psutil==5.*",
    "qrcode[pil]>=7.0.0",
    "dash>=2.0.0",
    "plotly>=5.0.0",
    "reportlab>=4.0.0",
    "prophet>=1.1.0",
    "pmdarima>=2.0.0",
    "schedule>=1.2.0",
    "emoji>=2.0.0",
    "textstat>=0.7.0",
    "lightgbm>=4.0.0",
    "xgboost>=3.0.0",
    "nltk>=3.8",
    "passlib[bcrypt]>=1.7.0",
    "stripe>=7.0.0"
]

[project.optional-dependencies]
dev = [
    "pytest==8.*",
    "pytest-asyncio==0.21.*",
    "httpx==0.24.*",
    "ruff==0.4.*",
    "aiosqlite==0.20.*",
]
