# AnalyticBot - Tool Configuration
# Dependencies are managed via pip-tools (requirements.in -> requirements.txt)

[tool.coverage.run]
source = ["apps", "core"]
branch = true
omit = [
    "infra/db/alembic/versions/*",
    "tests/*",
    "docs/*"
]

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E", "F", "I", "UP", "B"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"
