[tool.poetry]
name = "analytic-bot"
version = "0.1.0"
description = ""
authors = ["Udevs <info@udevs.io>"]
readme = "README.md"
packages = [{include = "bot"}]

[tool.poetry.dependencies]
python = "^3.11"
aiogram = "^3.10.0"
pydantic = "^2.8.2"
pydantic-settings = "^2.3.4"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.31"}
asyncpg = "^0.29.0"
alembic = "^1.13.2"
punq = "^0.7.0"
celery = {extras = ["redis"], version = "^5.4.0"}
redis = "^5.0.7"
fluent-runtime = "^0.4.0"
aiogram-i18n = "^1.4"
uvloop = "^0.19.0"
uvicorn = {extras = ["standard"], version = "^0.30.1"}
fastapi = "^0.116.1"
psycopg2-binary = "^2.9.9"
python-multipart = "^0.0.9"
fluent-compiler = "^0.4.0"
matplotlib = "^3.9.1"
python-dotenv = "^1.0.1"
sentry-sdk = "^2.9.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
pre-commit = "^3.7.1"
ruff = "^0.4.8"
mypy = "^1.10.0"
black = "^24.4.2"
fakeredis="^2.21.0"
pytest-cov="^4.1.0"
pip-audit = "^2.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
