[project]
name = "analyticbot"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name", email = "you@example.com"},
]
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "SQLAlchemy[asyncio]>=2.0.31,<3.0.0",
    "aiogram>=3.10.0,<4.0.0",
    "aiogram-i18n>=1.4,<2.0",
    "alembic>=1.13.2,<2.0.0",
    "asyncpg>=0.29.0,<0.30.0",
    "celery[redis]>=5.4.0,<6.0.0",
    "fastapi>=0.116.1,<0.117.0",
    "fluent-runtime>=0.4.0,<0.5.0",
    "matplotlib>=3.9.1,<4.0.0",
    "punq>=0.7.0,<0.8.0",
    "pydantic>=2.8.2,<3.0.0",
    "pydantic-settings>=2.3.4,<3.0.0",
    "python-dotenv>=1.0.1,<2.0.0",
    "redis>=5.0.7,<6.0.0",
    "sentry-sdk>=2.9.0,<3.0.0",
    "uvicorn[standard]>=0.30.1,<0.31.0",
    "pytest>=8.1.1,<9.0.0",
    "fakeredis>=2.21.0,<3.0.0",
    "pytest-cov>=4.1.0,<5.0.0",
]

[tool.poetry]
name = "analytic-bot"
version = "0.1.0"
description = ""
authors = ["Udevs <info@udevs.io>"]
readme = "README.md"
packages = [{include = "bot"}]

[tool.poetry.dependencies]
python = "^3.11"
aiogram = "^3.8.0"
pydantic = "^2.7.4"
pydantic-settings = "^2.3.4"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.30"}
asyncpg = "^0.29.0"
alembic = "^1.13.1"
punq = "^0.6.0"
celery = "^5.4.0"
redis = "^5.0.4"
fluent-runtime = "^0.4.0"
python-i18n = {extras = ["YAML"], version = "^0.3.9"}
uvloop = "^0.19.0"
uvicorn = "^0.30.1"
fastapi = "^0.116.1"
psycopg2-binary = "^2.9.9"
python-multipart = "^0.0.9"


[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
pre-commit = "^3.7.1"
ruff = "^0.4.8"
mypy = "^1.10.0"
black = "^24.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
