[project]
name = "analyticbot"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name", email = "you@example.com"},
]
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "SQLAlchemy[asyncio]>=2.0.31,<3.0.0",
    "aiogram>=3.10.0,<4.0.0",
    "aiogram-i18n>=1.4,<2.0",
    "alembic>=1.13.2,<2.0.0",
    "asyncpg>=0.29.0,<0.30.0",
    "celery[redis]>=5.4.0,<6.0.0",
    "fastapi>=0.116.1,<0.117.0",
    "fluent-runtime>=0.4.0,<0.5.0",
    "matplotlib>=3.9.1,<4.0.0",
    "punq>=0.7.0,<0.8.0",
    "pydantic>=2.8.2,<3.0.0",
    "pydantic-settings>=2.3.4,<3.0.0",
    "python-dotenv>=1.0.1,<2.0.0",
    "redis>=5.0.7,<6.0.0",
    "sentry-sdk>=2.9.0,<3.0.0",
    "uvicorn[standard]>=0.30.1,<0.31.0",
    "pytest>=8.1.1,<9.0.0",
    "pytest-asyncio>=0.23.5,<0.24.0",
    "fakeredis>=2.21.0,<3.0.0",
    "pytest-cov>=4.1.0,<5.0.0",
]

[tool.poetry]
name = "analyticbot"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
packages = [{include = "bot"}]


[tool.poetry.group.dev.dependencies]
flake8 = "^7.3.0"
mypy = "^1.17.1"
bandit = "^1.8.6"
safety = "^3.6.0"
pip-audit = "^2.9.0"
isort = "^6.0.1"
black = "^25.1.0"
locust = "^2.38.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
