apiVersion: v1
kind: Secret
metadata:
  name: {{ include "analyticbot.fullname" . }}-secret
  labels:
    {{- include "analyticbot.labels" . | nindent 4 }}
type: Opaque
data:
  # Telegram Bot Configuration
  BOT_TOKEN: {{ .Values.secrets.BOT_TOKEN | b64enc }}
  WEBHOOK_SECRET: {{ .Values.secrets.WEBHOOK_SECRET | b64enc }}
  
  # Database Credentials
  {{- if not .Values.postgresql.enabled }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | b64enc }}
  {{- end }}
  
  # Redis Credentials
  {{- if not .Values.redis.enabled }}
  REDIS_PASSWORD: {{ .Values.secrets.REDIS_PASSWORD | b64enc }}
  {{- end }}
  
  # AI/ML API Keys
  OPENAI_API_KEY: {{ .Values.secrets.OPENAI_API_KEY | b64enc }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.ANTHROPIC_API_KEY | b64enc }}
  GOOGLE_AI_API_KEY: {{ .Values.secrets.GOOGLE_AI_API_KEY | b64enc }}
  
  # Security Keys
  JWT_SECRET_KEY: {{ .Values.secrets.JWT_SECRET_KEY | b64enc }}
  ENCRYPTION_KEY: {{ .Values.secrets.ENCRYPTION_KEY | b64enc }}
  
  # External Service API Keys
  SENTRY_DSN: {{ .Values.secrets.SENTRY_DSN | b64enc }}
  DATADOG_API_KEY: {{ .Values.secrets.DATADOG_API_KEY | b64enc }}
  
  # OAuth Credentials
  GITHUB_CLIENT_SECRET: {{ .Values.secrets.GITHUB_CLIENT_SECRET | b64enc }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.GOOGLE_CLIENT_SECRET | b64enc }}
  
  # Webhook Secrets
  GITHUB_WEBHOOK_SECRET: {{ .Values.secrets.GITHUB_WEBHOOK_SECRET | b64enc }}
  SLACK_WEBHOOK_URL: {{ .Values.secrets.SLACK_WEBHOOK_URL | b64enc }}
  
  # Database Backup Credentials
  BACKUP_ENCRYPTION_KEY: {{ .Values.secrets.BACKUP_ENCRYPTION_KEY | b64enc }}
  S3_ACCESS_KEY: {{ .Values.secrets.S3_ACCESS_KEY | b64enc }}
  S3_SECRET_KEY: {{ .Values.secrets.S3_SECRET_KEY | b64enc }}
