{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "analyticbot.fullname" . }}-api-to-db
  labels:
    {{- include "analyticbot.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "analyticbot.selectorLabels" . | nindent 6 }}
      component: api
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgresql
              app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redis
              app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: 6379
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
    # Allow HTTPS outbound for external APIs
    - to: []
      ports:
        - protocol: TCP
          port: 443
---
# Allow Bot to communicate with API and Redis
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "analyticbot.fullname" . }}-bot-to-services
  labels:
    {{- include "analyticbot.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "analyticbot.selectorLabels" . | nindent 6 }}
      component: bot
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "analyticbot.selectorLabels" . | nindent 14 }}
              component: api
      ports:
        - protocol: TCP
          port: 8000
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redis
              app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: 6379
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
    # Allow HTTPS outbound for Telegram API
    - to: []
      ports:
        - protocol: TCP
          port: 443
---
# Allow ingress to API
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "analyticbot.fullname" . }}-api-ingress
  labels:
    {{- include "analyticbot.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "analyticbot.selectorLabels" . | nindent 6 }}
      component: api
  policyTypes:
    - Ingress
  ingress:
    # Allow ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8000
    # Allow monitoring
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
      ports:
        - protocol: TCP
          port: 8000
    # Allow same namespace (for health checks, etc.)
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8000
{{- end }}
