# Docker Compose configuration for MTProto Stats Loader (Phase 4.3)
# Usage: docker-compose -f docker-compose.yml -f docker-compose.mtproto.stats.yml up

version: '3.8'

services:
  mtproto-stats:
    build: .
    command: python -m apps.mtproto.tasks.load_stats
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped
    environment:
      - MTPROTO_ENABLED=true
      - MTPROTO_STATS_ENABLED=true
      # Configure your stats peers:
      # - MTPROTO_STATS_PEERS=["@channel1", "@channel2"]
      # - MTPROTO_STATS_CONCURRENCY=3
      # - MTPROTO_STATS_PERIOD_DAYS=30
    networks:
      - analyticbot_network
    profiles:
      - mtproto-stats

networks:
  analyticbot_network:
    external: true
