# AnalyticBot - Unified Docker Compose
# Development and local testing environment

services:
  # ---------- Database ----------
  db:
    image: postgres:16
    container_name: analyticbot-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-analytic_bot}
      POSTGRES_USER: ${POSTGRES_USER:-analytic}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change_me}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/db/init:/docker-entrypoint-initdb.d:ro
    # Production Environment Database - Port 
    ports:
      - "10100:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-analytic} -d ${POSTGRES_DB:-analytic_bot}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - database
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # ---------- Redis ----------
  redis:
    image: redis:7-alpine
    container_name: analyticbot-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    # Redis External Port - Production 10200
    ports:
      - "10200:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - database
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # ---------- MTProto Real Data Collection Service (Phase 2) ----------
  mtproto:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: api  # Reuse API image for now
    command: python scripts/mtproto_service.py service
    container_name: analyticbot-mtproto
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-analytic}:${POSTGRES_PASSWORD:-change_me}@db:5432/${POSTGRES_DB:-analytic_bot}
      REDIS_URL: redis://redis:6379/0
      # Phase 2 MTProto Real Data Collection - ENABLED
      MTPROTO_ENABLED: ${MTPROTO_ENABLED:-true}
      MTPROTO_HISTORY_ENABLED: ${MTPROTO_HISTORY_ENABLED:-true}
      MTPROTO_UPDATES_ENABLED: ${MTPROTO_UPDATES_ENABLED:-true}
      MTPROTO_STATS_ENABLED: ${MTPROTO_STATS_ENABLED:-true}
      # Telegram API credentials (required)
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_SESSION_NAME: ${TELEGRAM_SESSION_NAME:-analyticbot_session}
      # Collection settings with SAFE RATE LIMITING
      MTPROTO_PEERS: ${MTPROTO_PEERS:-}
      MTPROTO_HISTORY_LIMIT_PER_RUN: ${MTPROTO_HISTORY_LIMIT_PER_RUN:-50}  # Reduced for safety
      MTPROTO_CONCURRENCY: ${MTPROTO_CONCURRENCY:-1}  # Conservative for safety
      MTPROTO_SLEEP_THRESHOLD: ${MTPROTO_SLEEP_THRESHOLD:-2.0}  # Increased sleep
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    env_file:
      - ../.env.production
    depends_on:
      - db
      - redis
    volumes:
      - ./apps/mtproto:/app/apps/mtproto:ro
      - ./core:/app/core:ro
      - ./infra:/app/infra:ro
      - ./scripts:/app/scripts:ro
      - ./data:/app/data  # For session storage
    profiles:
      - mtproto  # Only start when explicitly requested
    healthcheck:
      test: ["CMD", "python", "-c", "import asyncio; asyncio.run(__import__('scripts.mtproto_service').MTProtoServiceManager().get_status())"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - backend   # Internal service communication (needs internet for Telegram API)
      - database  # Database access
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    restart: unless-stopped

  # ---------- Frontend Service ----------
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: frontend
    container_name: analyticbot-frontend
    ports:
      - "10300:80"
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://api:10400}
      VITE_SENTRY_DSN: ${VITE_SENTRY_DSN:-}
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - frontend  # Only needs frontend network access
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    restart: unless-stopped

  # ---------- Frontend Development (optional) ----------
  frontend-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: frontend-dev
    container_name: analyticbot-frontend-dev
    ports:
      - "10300:5173"
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://api:10400}
      VITE_SENTRY_DSN: ${VITE_SENTRY_DSN:-}
    volumes:
      - ./apps/frontend:/app:delegated
      - /app/node_modules
    depends_on:
      api:
        condition: service_healthy
    networks:
      - frontend  # Only needs frontend network access for dev
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    profiles:
      - dev
    restart: unless-stopped

  # ---------- API Service ----------
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: api
    command: uvicorn apps.api.main:app --host 0.0.0.0 --port 10400
    container_name: analyticbot-api
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-analytic}:${POSTGRES_PASSWORD:-change_me}@db:5432/${POSTGRES_DB:-analytic_bot}
      REDIS_URL: redis://redis:6379/0
    env_file:
      - ../.env.production
    ports:
      - "10400:10400"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10400/health"]
      interval: 10s
      timeout: 3s
      retries: 10
    volumes:
      - ./var/results:/app/results
    networks:
      - frontend  # Exposed to external traffic
      - backend   # Communicates with internal services
      - database  # Direct database access
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    restart: unless-stopped

  # ---------- Bot Service ----------
  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: bot
    command: python -m apps.bot.run_bot
    container_name: analyticbot-bot
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-analytic}:${POSTGRES_PASSWORD:-change_me}@db:5432/${POSTGRES_DB:-analytic_bot}
      REDIS_URL: redis://redis:6379/0
    env_file:
      - ../.env.production
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://api:10400/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - backend   # Internal service communication
      - database  # Database access
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    restart: unless-stopped

  # ---------- Celery Worker (optional) ----------
  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: worker
    command: celery -A infra.celery.celery_app worker -l info
    container_name: analyticbot-worker
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-analytic}:${POSTGRES_PASSWORD:-change_me}@db:5432/${POSTGRES_DB:-analytic_bot}
      REDIS_URL: redis://redis:6379/0
    env_file:
      - ../.env.production
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "celery", "-A", "infra.celery.celery_app", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - backend   # Internal service communication
      - database  # Database access
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    restart: unless-stopped
    profiles:
      - full

  # ---------- Celery Beat (optional) ----------
  beat:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: beat
    command: celery -A infra.celery.celery_app beat -l info
    container_name: analyticbot-beat
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-analytic}:${POSTGRES_PASSWORD:-change_me}@db:5432/${POSTGRES_DB:-analytic_bot}
      REDIS_URL: redis://redis:6379/0
    env_file:
      - ../.env.production
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "celery", "-A", "infra.celery.celery_app", "inspect", "registered"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - backend   # Internal service communication
      - database  # Database access
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.125'
    restart: unless-stopped
    profiles:
      - full

volumes:
  pgdata:
    name: analyticbot_pgdata
  redisdata:
    name: analyticbot_redisdata

networks:
  # Frontend network - for user-facing services (API, Frontend)
  frontend:
    driver: bridge
    name: analyticbot_frontend
    ipam:
      config:
        - subnet: 172.20.1.0/24
  
  # Backend network - for internal service communication
  backend:
    driver: bridge
    name: analyticbot_backend
    internal: false  # Allow internet access for external API calls
    ipam:
      config:
        - subnet: 172.20.2.0/24
  
  # Database network - isolated for data services only
  database:
    driver: bridge
    name: analyticbot_database
    internal: true  # No internet access - maximum security
    ipam:
      config:
        - subnet: 172.20.3.0/24
