# 🚀 PRODUCTION DEPLOYMENT PIPELINE CONFIGURATION
# Safe development-to-production deployment with user data protection

version: '3.8'

# This file defines the complete deployment pipeline stages
# Used by CI/CD systems and deployment scripts

# ========================================
# PIPELINE STAGES CONFIGURATION
# ========================================

stages:
  - name: "development"
    database:
      type: "local"
      backup_required: false
      migration_validation: "basic"
    testing:
      - unit_tests
      - integration_tests
    deployment:
      method: "local"
      rollback_strategy: "git_reset"

  - name: "testing"
    database:
      type: "staging"
      backup_required: true
      migration_validation: "comprehensive"
      data_source: "production_sanitized"
    testing:
      - unit_tests
      - integration_tests
      - performance_tests
      - security_tests
    deployment:
      method: "docker_compose"
      rollback_strategy: "backup_restore"

  - name: "staging"
    database:
      type: "production_clone"
      backup_required: true
      migration_validation: "production_simulation"
      data_source: "production_full_clone"
    testing:
      - unit_tests
      - integration_tests
      - performance_tests
      - security_tests
      - load_tests
      - user_acceptance_tests
    deployment:
      method: "blue_green"
      rollback_strategy: "blue_green_switch"

  - name: "pre_production"
    database:
      type: "production_replica"
      backup_required: true
      migration_validation: "timing_analysis"
      data_source: "production_replica"
    testing:
      - smoke_tests
      - performance_benchmarks
      - security_scans
      - compliance_checks
    deployment:
      method: "canary"
      rollback_strategy: "immediate_switchback"

  - name: "production"
    database:
      type: "production"
      backup_required: true
      migration_validation: "zero_downtime"
      data_source: "live"
    testing:
      - smoke_tests
      - health_checks
      - monitoring_validation
      - business_metrics_validation
    deployment:
      method: "blue_green_zero_downtime"
      rollback_strategy: "automated_failback"

# ========================================
# SAFETY GATES CONFIGURATION
# ========================================

safety_gates:
  pre_deployment:
    - database_connectivity_check
    - backup_creation_and_validation
    - disk_space_validation
    - long_running_transaction_check
    - migration_syntax_validation
    - rollback_plan_verification
    - team_notification

  during_deployment:
    - migration_timeout_monitoring
    - database_performance_monitoring
    - application_health_monitoring
    - user_impact_monitoring
    - automated_rollback_triggers

  post_deployment:
    - data_integrity_validation
    - foreign_key_constraint_validation
    - application_functionality_testing
    - performance_baseline_comparison
    - user_authentication_testing
    - business_metrics_validation
    - 24_hour_monitoring_period

# ========================================
# ROLLBACK TRIGGERS CONFIGURATION
# ========================================

automatic_rollback_triggers:
  - migration_execution_time_exceeded: "60 minutes"
  - data_loss_detected: "any amount"
  - application_health_failure_rate: "> 50%"
  - database_performance_degradation: "> 30%"
  - user_authentication_failure_rate: "> 5%"
  - foreign_key_constraint_violations: "> 0"
  - critical_business_metric_drop: "> 20%"

manual_rollback_conditions:
  - unexpected_user_behavior_reports
  - payment_processing_anomalies
  - critical_feature_unavailability
  - team_decision_based_on_monitoring

# ========================================
# MONITORING CONFIGURATION
# ========================================

monitoring:
  database_metrics:
    - connection_count
    - query_execution_time
    - lock_wait_time
    - replication_lag
    - disk_usage
    - cache_hit_ratio

  application_metrics:
    - response_time
    - error_rate
    - throughput
    - memory_usage
    - cpu_usage
    - active_user_sessions

  business_metrics:
    - user_registration_rate
    - payment_success_rate
    - channel_creation_rate
    - post_scheduling_rate
    - api_usage_patterns

  alerts:
    critical:
      - data_loss_detected
      - migration_timeout
      - service_unavailability
      - database_connection_failure
    warning:
      - performance_degradation
      - high_error_rate
      - unusual_traffic_patterns
      - backup_failure

# ========================================
# BACKUP STRATEGY CONFIGURATION
# ========================================

backup_strategy:
  tiers:
    tier_1_hot:
      method: "wal_streaming"
      frequency: "continuous"
      retention: "7_days"
      rto: "< 5 minutes"
      rpo: "< 1 minute"

    tier_2_warm:
      method: "incremental_basebackup"
      frequency: "hourly"
      retention: "30_days"
      rto: "< 30 minutes"
      rpo: "< 1 hour"

    tier_3_cold:
      method: "full_pg_dump"
      frequency: "daily"
      retention: "90_days"
      rto: "< 2 hours"
      rpo: "< 24 hours"

  validation:
    - backup_integrity_check
    - restore_test_on_staging
    - cross_region_replication_verification
    - encryption_validation

# ========================================
# ENVIRONMENT CONFIGURATIONS
# ========================================

environments:
  development:
    database_url: "postgresql://dev_user:dev_pass@localhost:5432/analyticbot_dev"
    migration_timeout: 300  # 5 minutes
    backup_retention: 7     # days
    monitoring_level: "basic"

  testing:
    database_url: "postgresql://test_user:test_pass@test-db:5432/analyticbot_test"
    migration_timeout: 600  # 10 minutes
    backup_retention: 14    # days
    monitoring_level: "comprehensive"

  staging:
    database_url: "postgresql://staging_user:staging_pass@staging-db:5432/analyticbot_staging"
    migration_timeout: 1200 # 20 minutes
    backup_retention: 30    # days
    monitoring_level: "production_like"

  production:
    database_url: "${DATABASE_URL}"  # From environment variables
    migration_timeout: 1800 # 30 minutes
    backup_retention: 90    # days
    monitoring_level: "full"

# ========================================
# DEPLOYMENT METHODS CONFIGURATION
# ========================================

deployment_methods:
  blue_green_zero_downtime:
    description: "Zero-downtime deployment using blue-green database strategy"
    steps:
      - create_green_environment
      - sync_data_to_green
      - apply_migrations_to_green
      - validate_green_environment
      - switch_traffic_to_green
      - monitor_green_environment
      - decommission_blue_after_24h

  canary:
    description: "Gradual rollout to subset of users"
    traffic_split:
      - "5% for 1 hour"
      - "25% for 2 hours"
      - "50% for 4 hours"
      - "100% after validation"

  rolling:
    description: "Sequential instance updates with health checks"
    batch_size: 1
    health_check_interval: 30  # seconds
    rollback_on_failure: true

# ========================================
# SECURITY CONFIGURATION
# ========================================

security:
  data_protection:
    - encrypt_backups: true
    - sanitize_staging_data: true
    - audit_data_access: true
    - compliance_validation: true

  access_control:
    - production_access_restricted: true
    - deployment_approval_required: true
    - audit_trail_mandatory: true
    - mfa_required_for_production: true

# ========================================
# COMPLIANCE AND AUDITING
# ========================================

compliance:
  requirements:
    - gdpr_compliance
    - data_retention_policies
    - audit_trail_maintenance
    - security_scanning

  reporting:
    - deployment_success_metrics
    - data_integrity_reports
    - performance_impact_analysis
    - security_compliance_status

# ========================================
# NOTIFICATION CONFIGURATION
# ========================================

notifications:
  channels:
    - slack: "#deployments"
    - email: "team@analyticbot.com"
    - webhook: "https://monitoring.analyticbot.com/webhooks/deployment"

  events:
    pre_deployment:
      - deployment_started
      - backup_created
      - safety_checks_completed

    during_deployment:
      - migration_progress_updates
      - performance_alerts
      - error_notifications

    post_deployment:
      - deployment_completed
      - validation_results
      - monitoring_summary
      - rollback_availability_notice
