name: Apply Patch from Comment

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  apply:
    # faqat /apply-patch bo'lsa ishlaydi
    if: contains(github.event.comment.body, '/apply-patch')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Komment yozgan userda write/maintain/admin borligini tekshir
      - name: Authorize commenter
        id: auth
        uses: actions/github-script@v7
        with:
          script: |
            const login = context.payload.comment.user.login;
            const { data } = await github.rest.repos.getCollaboratorPermissionLevel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              username: login,
            });
            const perm = data.permission; // admin|maintain|write|triage|read|none
            core.info(`@${login} permission: ${perm}`);
            core.setOutput('login', login);
            if (!['admin','maintain','write'].includes(perm)) {
              core.setFailed(`User @${login} lacks write permission (has: ${perm}).`);
            }

      # Kommentdan base, branch va ```patch``` blokni ajratib ol
      - name: Parse patch block
        id: parse
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.comment.body;
            const base = (body.match(/base:\s*([^\s]+)/i)?.[1]) || 'main';
            const branch = (body.match(/branch:\s*([^\s]+)/i)?.[1]) || `auto/patch-${Date.now()}`;
            const m = body.match(/```patch\s*([\s\S]*?)```/i);
            if (!m) core.setFailed('No ```patch``` fenced block found in the comment.');
            require('fs').writeFileSync('patch.diff', m[1], 'utf8');
            core.setOutput('base', base);
            core.setOutput('branch', branch);

      - name: Apply patch & push
        run: |
          set -e
          git config user.name "${{ steps.auth.outputs.login }} (bot)"
          git config user.email "${{ steps.auth.outputs.login }}@users.noreply.github.com"
          git checkout "${{ steps.parse.outputs.base }}"
          git checkout -b "${{ steps.parse.outputs.branch }}"
          git apply -3 --whitespace=fix patch.diff
          git add -A
          git commit -m "chore: apply patch from comment by @${{ steps.auth.outputs.login }}"
          git push origin "${{ steps.parse.outputs.branch }}"

      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ steps.parse.outputs.branch }}
          base: ${{ steps.parse.outputs.base }}
          title: "chore: apply patch from comment by @${{ steps.auth.outputs.login }}"
          body: "Auto-applied patch from [comment](${{ github.event.comment.html_url }})."
