name: Auto AI-Fix on CI failure

on:
  workflow_run:
    workflows: ["CI"]   # sizning asosiy workflow nomi: ci.yml dagi `name: CI`
    types: [completed]

jobs:
  tag-ai-fix:
    if: github.event.workflow_run.conclusion == 'failure'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: read
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const run = context.payload.workflow_run;
            const prs = run.pull_requests || [];
            if (!prs.length) return;  // push build bo'lsa, chiqib ket
            const prNum = prs[0].number;
            // Fork PRlarda label qo'yishdan saqlaning (xohlasangiz shart qo'shing)
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNum,
              labels: ['ai-fix']
            });
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNum,
              body: "CI failed → labeling `ai-fix` to trigger AI Fixer v2."
            });
