name: Autofix (ruff)

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
  workflow_dispatch:

jobs:
  autofix:
    # PR’da 'autofix' label bo‘lsa yoki qo‘lda ishga tushirilsa
    if: github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'autofix')
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tools
        run: |
          python -m pip install -U pip
          pip install ruff

      - name: Ruff fix
        run: ruff check . --fix

      - name: Ruff format
        run: ruff format .

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-fix with ruff"
          branch: ${{ github.head_ref || github.ref_name }}
