name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11", "3.12" ]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check deps are compiled
        run: |
          pip install pip-tools
          pip-compile --no-upgrade -o requirements.txt requirements.in
          pip-compile --no-upgrade -o requirements.prod.txt requirements.prod.in
          git diff --exit-code requirements.txt requirements.prod.txt

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-${{ matrix.python-version }}-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compile all Python modules
        run: python -m compileall -x 'apps/frontend/node_modules' .

      - name: Import smokes
        run: |
          python -c "import apps.api.main; print('API OK')"
          python -c "import apps.bot.run_bot; print('BOT OK')"

      - name: Run tests with coverage
        run: |
          pip install pytest-cov
          pytest --cov=apps --cov=core --cov-report=term-missing --cov-report=xml --cov-fail-under=70 tests/test_health.py tests/test_layered_architecture.py

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

      - name: Security audit
        run: |
          pip install safety
          safety check --ignore=12345 || echo "⚠️ Security vulnerabilities found, review required"

      - name: Check pre-commit configuration
        id: precommit-check
        run: |
          if [ -f .pre-commit-config.yaml ]; then
            echo "has-precommit=true" >> $GITHUB_OUTPUT
          else
            echo "has-precommit=false" >> $GITHUB_OUTPUT
          fi

      - name: Install pre-commit
        if: steps.precommit-check.outputs.has-precommit == 'true'
        run: |
          pip install pre-commit

      - name: Run pre-commit
        if: steps.precommit-check.outputs.has-precommit == 'true'
        run: |
          pre-commit run --all-files

      - name: Lint with ruff
        run: |
          ruff check .

      - name: Format check with ruff
        run: |
          ruff format --check .

      - name: Run integration tests
        run: |
          pytest tests/test_layered_architecture.py tests/test_health.py -v

  # Optional Docker build smoke test
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -f infra/docker/Dockerfile --target api -t analyticbot:test .
          echo "✅ Docker build successful"

      - name: Test Docker image
        run: |
          docker run --rm analyticbot:test python -c "
          import apps.api.main
          import apps.bot.run_bot
          print('✅ Docker image imports working')
          "