name: Compose Verify

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  verify:
    if: contains(join(github.event.pull_request.labels.*.name, ','), 'compose-verify:on')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare .env
        run: cp .env.example .env

      - name: Build & start (Compose)
        run: docker compose up -d --build

      - name: Show services
        run: docker compose ps

      - name: Wait for Postgres (inside compose)
        run: |
          for i in {1..60}; do
            docker compose exec -T postgres pg_isready -U "${POSTGRES_USER:-analytic}" -d "${POSTGRES_DB:-analytic_bot}" && break
            sleep 2
          done

      - name: Print API DATABASE_URL
        run: docker compose exec -T api /bin/sh -lc 'echo "$DATABASE_URL"'

      - name: Run DB migrations (inside api)
        run: docker compose exec -T api alembic upgrade head

      - name: Smoke check (plans table)
        run: docker compose exec -T postgres psql -U "${POSTGRES_USER:-analytic}" -d "${POSTGRES_DB:-analytic_bot}" -c "SELECT COUNT(*) FROM plans;"

      - name: Compose logs (artifact)
        if: always()
        run: docker compose logs > compose-logs.txt


      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: compose-logs
          path: compose-logs.txt

      - name: Compose down
        if: always()
        run: docker compose down -v --remove-orphans
