name: Nightly Security
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Gitleaks (secrets scan)
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-banner --redact

      - name: Trivy FS scan (repo)
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
            | sh -s -- -b /usr/local/bin
          trivy fs --exit-code 1 --severity CRITICAL,HIGH .

      - name: CodeQL init
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: CodeQL analyze
        uses: github/codeql-action/analyze@v3
