name: Nightly Security

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

# <<< MUHIM: TOKEN RUXSATLARI
permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  security:
    runs-on: ubuntu-latest

    # (ixtiyoriy) job darajasida ham takrorlab qo‘yish mumkin
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4

      - name: Gitleaks (secrets scan)
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-banner --redact

      - name: Trivy FS scan (repo)
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
            | sh -s -- -b /usr/local/bin
          trivy fs --exit-code 1 --severity CRITICAL,HIGH .

      - name: CodeQL init
        uses: github/codeql-action/init@v3
        with:
          languages: python
          # cleanup-level parametriasini olib tashladik

      - name: CodeQL analyze
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:python"   # ixtiyoriy, lekin foydali
          upload: true                   # default true, aniq ko‘rsatish zarar qilmaydi
